baseurl = "https://www.nyasaki.dev/"
theme = "harbor"
title = "Dev Blog"
author = "Marcel Walk"
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Marcel Walk"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"
  
[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "/archives/"
  weight = 3

[[params.social]]
  name="GitHub"
  url="https://github.com/MarcelWalk"
  icon="fab fa-github fa-lg"

[[params.social]]
  name="LinkedIn"
  url="https://www.linkedin.com/in/marcel-walk/"
  icon="fab fa-linkedin fa-lg"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

[params.logo]
  url = "icon.png"
  width = 50
  height = 50
  alt = "Logo"